import React,{useMemo,useState} from 'react';
import {Plus,Search,FileText,Clock3,FolderOpen,BookOpen,ChevronRight} from 'lucide-react';
export function Brand(){return <div className="brand"><div className="logo" aria-hidden="true">B<span>·</span></div><div><b>TeX<span>Bea</span></b><small>L’atelier scientifique</small></div></div>}
export function ProjectDialog({onClose,onCreate}){const[name,setName]=useState(''),[waiting,setWaiting]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();setWaiting(true);try{await onCreate(name.trim());onClose()}catch(e){setError(e.message)}finally{setWaiting(false)}}return <div className="modalBack"><section className="modal create-modal" role="dialog" aria-modal="true" aria-labelledby="create-title"><div className="modalHead"><h2 id="create-title">Un nouveau projet</h2><button onClick={onClose} aria-label="Fermer">×</button></div><p>Un document vierge, prêt pour tes idées.</p><form onSubmit={submit}><label htmlFor="project-name">Nom du projet</label><input id="project-name" autoFocus required maxLength={80} placeholder="Rapport, mémoire, article…" value={name} onChange={e=>setName(e.target.value)}/>{error&&<p className="error">{error}</p>}<button className="primary" disabled={waiting||!name.trim()}>{waiting?'Création…':'Créer le projet'}</button></form></section></div>}
export default function ProjectLibrary({projects,onOpen,onNew,mode}){const[query,setQuery]=useState(''),[sort,setSort]=useState('recent');const list=useMemo(()=>projects.filter(p=>p.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0)),[projects,query,sort]);const recent=[...projects].sort((a,b)=>Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0))[0];function date(value){return value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium'}).format(new Date(value)):'—'}return <div className="library">
<header className="library-header"><Brand/><div className="library-tabs"><span className="active">Mes projets</span><span className="library-mode">{mode?'Espace personnel':'Mon atelier'}</span></div><div className="account-chip">B</div></header>
<div className="library-content"><div className="library-title"><div><div className="eyebrow">TON ESPACE DE TRAVAIL</div><h1>Des idées aux <em>pages.</em></h1><p>Retrouve tes documents et reprends le fil de ton travail.</p></div><button className="primary new-project" onClick={onNew}><Plus size={18}/> Nouveau projet</button></div>
<div className="library-grid"><section className="project-panel"><div className="project-controls"><label className="project-search"><Search size={18}/><input aria-label="Rechercher un projet" placeholder="Rechercher un projet…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Trier les projets" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Plus récents</option><option value="name">Nom A–Z</option></select></div><div className="project-table-title"><h2>Tous les projets <span>{projects.length}</span></h2><span>Dernière modification</span></div><div className="project-list">{list.map((p,i)=><button className="project-row" key={p.id} onClick={()=>onOpen(p.id)}><span className={'project-symbol tone-'+i%3}><FileText size={20}/></span><span className="project-name"><b>{p.name}</b><small>{p.fileCount||0} fichier{p.fileCount>1?'s':''} · LaTeX</small></span><time dateTime={p.updatedAt}>{date(p.updatedAt)}</time><ChevronRight size={17}/></button>)}{!list.length&&<div className="library-empty"><FolderOpen size={32}/><h3>{query?'Aucun résultat':'Ton premier projet commence ici'}</h3><p>{query?'Essaie un autre nom.':'Crée un projet pour ouvrir l’éditeur LaTeX.'}</p>{!query&&<button onClick={onNew}>Créer un projet</button>}</div>}</div><footer className="project-panel-footer"><span>{list.length} projet{list.length>1?'s':''}</span><span>Un espace pour tes idées.</span></footer></section>
<aside className="library-aside">{recent&&<section className="resume-card"><div className="resume-label"><Clock3 size={16}/> REPRENDRE</div><div className="document-mark" aria-hidden="true"><FileText size={48} strokeWidth={1}/></div><h2>{recent.name}</h2><p>Modifié le {date(recent.updatedAt)}</p><button onClick={()=>onOpen(recent.id)}>Ouvrir l’atelier <FolderOpen size={17}/></button></section>}<section className="workspace-note"><BookOpen size={21}/><h3>Ton atelier, ton rythme.</h3><p>Écris en LaTeX, compile ton PDF et retrouve le code d’un double-clic sur le texte.</p><small>{mode?'Les projets sont conservés dans ce navigateur.':'Les projets sont sauvegardés dans ton espace.'}</small></section><div className="library-stat"><b>{projects.reduce((n,p)=>n+(p.fileCount||0),0)}</b><span>fichiers dans ton atelier</span></div></aside></div>
<footer className="library-footer"><span>TeXBea</span><span>Écrire. Comprendre. Transmettre.</span></footer></div></div>}
